---
title: "TALLER PARA LA PREDICCIÓN DE LA DISTRIBUCIÓN GEOGRÁFICA DE LAS ESPECIES COMO HERRAMIENTA PARA LA TOMA DE DECISIONES"

output:

html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
---

Los modelos de distribución de especies (SDM por sus siglas en inglés) son modelos computacionales que se utilizan para predecir la distribución geográfica potencial de las especies en función de las variables ambientales. En este sentido los  modelos permiten establecer relaciones entre los registros de ocurrencia observados de una especie y los factores ambientales, como la temperatura, la precipitación, la elevación y la cobertura del suelo, por lo que se denominan modelos correlativos. Al analizar las ocurrencias conocidas de una especie en relación con estas variables ambientales, los SDM pueden generar predicciones sobre dónde es probable que ocurra la especie en áreas donde faltan observaciones.

El objetivo de este taller es fortalecer las capacidades y experiencias institucionales en torno a la generación de SDM, usando una herramienta promovida por una beca de National Geographic Society (Developing an integrated species distribution modelling system to identify complementary conservation areas in Colombia; AI for Earth Innovation Grant NGS-86896T-21). Durante el encuentro se realizarán tanto presentaciones magistrales como ejercicios prácticos en donde se abordará lo que son los Modelos de Distribución de Especies y cómo estos pueden ser utilizados para comprender los requisitos ecológicos y las preferencias de hábitat de las especies, identificar áreas de gran riqueza de especies o biodiversidad, evaluar los impactos potenciales del cambio climático en la distribución de especies e informar estrategias de conservación y gestión. 

De igual forma se identificarán algunas de las herramientas más  usadas para la generación de estas hipótesis de distribución y se mostrarán las metodologías usadas por el Instituto para automatizar este proceso. Finalmente se presentará a BioModelos como una de las herramientas generadas por el Instituto para la obtención de SDM de manera colaborativa y se realizarán espacios de discusión en los cuales se identifiquen las fortalezas y debilidades en el uso de esta información para la toma de decisiones.
El encuentro se realizará en Español. 


## AGENDA 

### Día 1 

**8:30-9:00 am:** Llegada de los asistentes. (Todos)

**9:00 am**: Palabras de Bienvenida y misión Institucional

**9:30 am-9:50 am**: Proyecto “Developing an integrated species distribution modelling system to identify complementary conservation areas in Colombia; AI for Earth Innovation Grant NGS-86896T-21”.

**9:50 am-10:20 am**: Flujo de modelamiento de distribuciones de especies

**10:20-10:40 am**: Receso.

**10:40-11:00 am**: Presentación BioModelos

**11:00-11:20 am**: Presentación Herramienta - biomodelos-sdm tool

**11:20-12:30 pm**: Taller 1. Instalación de paquetes para el desarrollo del taller siguiendo las [instrucciones](setup.html) del paquete biomodelos-sdm tool

**12:30-1:30 pm**: Almuerzo

**1:30-3:00 pm**: Taller 2. Identificación de la distribución potencial de especies con un número adecuado de registros [*Chlorochrysa nitidissima*](working-example-1.html) y con pocos registros [*Bucco noanamae*](working-example-2.html).

**3:30-3:40 pm**: Receso

**3:40-4:30 pm**: Taller 3. Identificación de la distribución potencial al proyectar a una extensión espacial diferente [Myiopsitta monachus](working-example-3.html) y periodos temporales diferentes [Euphonia concinna](working-example-4.html)

**4:30-5:00 pm**: Lecciones aprendidas y conclusiones de la sesión (Todos)

**5:00 pm**: Cierre del taller


### Día 2


**8:30-9:00 am**: Llegada de los asistentes.

**9:00-10:00 am**: Taller 4. Identificación de la distribución potencial actual y futura, [automatizada para varias especies](working-example-5.html).

**10:30 am-11:00 am**: Paseo por Wallace, paseo por BioModelos GEE

**11:00-11:20 am**: Receso

**11:20-11:50 pm**: BioModelos como herramienta para la apropiación social del conocimiento. 

**11:50-12:30 pm**: Lecciones aprendidas y conclusiones de la sesión (Todos)

**12:30-1:30 pm**: Almuerzo

**1:30 pm- 2:00 pm**: Paseo por BioTablero, despedida


## Contacto  
 
Cualquier pregunta o duda, por favor no duden en contactar a: Elkin A. Noguera-Urbano enoguera@humboldt.org.co y a Carlos Jair Muñoz cmunoz@humboldt.org.co.


